CREATE TABLE book (

    BkID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL ,
    Book_Title VARCHAR NOT NULL UNIQUE,
    Author VARCHAR(100) NOT NULL,
    Publisher VARCHAR NOT NULL ,
    Price DOUBLE NOT NULL,
    Category VARCHAR(200) NOT NULL
);

