CREATE TABLE customers (

    customerID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    customerName VARCHAR(255) NOT NULL UNIQUE ,
    contactName VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL ,
    city VARCHAR(255) NOT NULL ,
    postalCode INT UNSIGNED NOT NULL ,
    country VARCHAR(255) NOT NULL

);